[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basedpyright>=1.29.1",
    "marimo>=0.13.2",
    "quarto-cli>=1.7.29",
    "ruff>=0.11.7",
]

[tool.marimo.runtime]
pythonpath = ["scripts"]
